buybacks/urls.py
from django.urls import path
from django.conf.urls import url

from . import views


app_name = "buybacks"

urlpatterns = [
    path("", views.index, name="index"),
    path("setup", views.setup, name="setup"),
    url(
        r"^item_autocomplete/$",
        views.item_autocomplete,
        name="item_autocomplete",
    ),
    path("my_notifications", views.my_notifications, name="my_notifications"),
    path("my_stats", views.my_stats, name="my_stats"),
    url(
        r"^notification/(?P<notification_pk>[0-9]+)/remove$",
        views.notification_remove,
        name="notification_remove",
    ),
    url(
        r"^notification/(?P<notification_pk>[0-9]+)/edit$",
        views.notification_edit,
        name="notification_edit",
    ),
    path("program_add", views.program_add, name="program_add"),
    path("program_add_2", views.program_add_2, name="program_add_2"),
    url(
        r"^program/(?P<program_pk>[0-9]+)/edit$",
        views.program_edit,
        name="program_edit",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)$",
        views.program,
        name="program",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/remove$",
        views.program_remove,
        name="program_remove",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/calculate$",
        views.program_calculate,
        name="program_calculate",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/stats$",
        views.program_stats,
        name="program_stats",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/notify$",
        views.program_notify,
        name="program_notify",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/notifications$",
        views.program_notifications,
        name="program_notifications",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/add_item$",
        views.program_add_item,
        name="program_add_item",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/add_location$",
        views.program_add_location,
        name="program_add_location",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/remove_item/(?P<item_type_pk>[0-9]+)$",
        views.program_remove_item,
        name="program_remove_item",
    ),
    url(
        r"^program/(?P<program_pk>[0-9]+)/remove_location/(?P<office_pk>[0-9]+)$",
        views.program_remove_location,
        name="program_remove_location",
    ),
]

buybacks/views/notifications.py
import json

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect, render
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
from django.utils.html import format_html

from eveuniverse.models import EveType

from ..models import Notification, Program, ProgramLocation
from ..utils import messages_plus
from ..forms import NotificationForm


@csrf_exempt
@login_required
@permission_required("buybacks.basic_access")
def program_notify(request, program_pk):
    program = Program.objects.filter(pk=program_pk).first()

    if request.method != "POST" or program is None:
        return HttpResponseBadRequest("")

    data = json.loads(request.body)

    program_location = ProgramLocation.objects.filter(
        program=program, id=data["program_location"]
    ).first()

    if program_location is None:
        return HttpResponseBadRequest("")

    notification = Notification.objects.create(
        program_location=program_location,
        user=request.user,
        total=data["total"],
        items=json.dumps(data["items"]),
    )

    if notification is None:
        return HttpResponseBadRequest("")
    else:
        messages_plus.success(
            request,
            format_html(
                "Created a notification for buyback program <strong>{}</strong>",
                program.name,
            ),
        )

    return JsonResponse({})


@login_required
@permission_required("buybacks.basic_access")
def my_notifications(request):
    notifications = Notification.objects.filter(
        user=request.user,
    )

    typeids = set()
    items = {}

    for notification in notifications:
        data = json.loads(notification.items)

        for type_id in data:
            typeids.add(type_id)

    types = EveType.objects.filter(pk__in=typeids)

    for item in types:
        items[str(item.id)] = item.name

    context = {
        "bb_notifications": notifications,
        "items": items,
        "mine": True,
    }

    return render(request, "buybacks/notifications.html", context)


@login_required
@permission_required("buybacks.basic_access")
def notification_remove(request, notification_pk):
    mine = request.GET.get("mine", "True") == "True"

    notification = Notification.objects.filter(pk=notification_pk)

    if mine:
        notification.filter(user=request.user).delete()
    elif request.user.has_perm("buybacks.manage_programs"):
        notification = notification.first()
        notification.delete()

        return redirect(
            "buybacks:program_notifications",
            program_pk=notification.program_location.program.id,
        )

    return redirect("buybacks:my_notifications")


@login_required
@permission_required("buybacks.basic_access")
def notification_edit(request, notification_pk):
    mine = request.GET.get("mine", "True") == "True"

    notification = Notification.objects.filter(pk=notification_pk)

    if not mine and not request.user.has_perm("buybacks.manage_programs"):
        return redirect("buybacks:index")

    if mine:
        notification = notification.filter(user=request.user)

    notification = notification.first()

    if notification is None:
        return redirect("buybacks:my_notifications")

    if request.method != "POST":
        form = NotificationForm(notification=notification)
    else:
        form = NotificationForm(request.POST, notification=notification)

        if form.is_valid():
            notification.program_location = form.cleaned_data["office"]

            try:
                notification.save()

                messages_plus.success(
                    request,
                    format_html(
                        "Edited notification location to <strong>{}</strong>",
                        notification.program_location,
                    ),
                )

                if mine:
                    return redirect("buybacks:my_notifications")
                else:
                    return redirect(
                        "buybacks:program_notifications",
                        program_pk=notification.program_location.program.id,
                    )

            except Exception:
                messages_plus.error(
                    request,
                    "Failed to edit location of the notification",
                )

    context = {
        "corporation": notification.program_location.program.corporation.corporation,
        "form": form,
        "notification": notification,
        "mine": mine,
    }

    return render(request, "buybacks/notification_edit.html", context)


@login_required
@permission_required("buybacks.basic_access")
def program_notifications(request, program_pk):
    notifications = Notification.objects.filter(
        program_location__program__id=program_pk,
    )

    typeids = set()
    items = {}

    for notification in notifications:
        data = json.loads(notification.items)

        for type_id in data:
            typeids.add(type_id)

    types = EveType.objects.filter(pk__in=typeids)

    for item in types:
        items[str(item.id)] = item.name

    context = {
        "bb_notifications": notifications,
        "items": items,
        "mine": False,
    }

    return render(request, "buybacks/notifications.html", context)

buybacks/views/programs.py
import math

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect, render
from django.utils.html import format_html
from django.utils.translation import gettext_lazy
from django.urls import reverse
from esi.models import Token
from esi.decorators import token_required
from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo

from ..helpers import evemarketer
from ..models import Program, ProgramItem, ProgramLocation, Corporation
from ..forms import ProgramForm, ProgramItemForm, ProgramLocationForm, CalculatorForm
from ..utils import messages_plus

ADD_PROGRAM_TOKEN_TAG = "buybacks_add_program_token"


@login_required
@permission_required("buybacks.basic_access")
def program_calculate(request, program_pk):
    program = Program.objects.filter(pk=program_pk).first()
    data = {}
    value = {}
    typeids = {}
    program_location = None
    total = 0

    if program is None:
        return redirect("buybacks:index")

    if request.method != "POST":
        form = CalculatorForm(program=program)
    else:
        form = CalculatorForm(request.POST, program=program)

        if form.is_valid():
            office = form.cleaned_data["office"]
            items = form.cleaned_data["items"]

            program_location = ProgramLocation.objects.filter(
                program=program,
                office__location__name=office,
            ).first()

            for item in items.split("\n"):
                parts = item.split("\t")

                if len(parts) >= 2:
                    name = parts[0]
                    quantity = int(
                        parts[1]
                        .replace(" ", "")
                        .replace(".", "")
                        .replace("\xa0", "")
                        .replace("\r", "")
                        .replace(",","")
                    )

                    if name in data:
                        data[name] += quantity
                    else:
                        data[name] = quantity

            brokerages = {}

            program_items = ProgramItem.objects.filter(
                program=program, item_type__name__in=data.keys()
            )

            for item in program_items:
                if not item.use_refined_value:
                    brokerages[item.item_type.name] = item.brokerage
                    typeids[item.item_type.name] = item.item_type.id

            prices = evemarketer(typeids.values())

            for name in brokerages:
                item_value = (
                    (100 - brokerages[name])
                    / 100
                    * data[name]
                    * prices[typeids[name]]["buy"]
                )

                value[name] = item_value
                total += item_value

            total = math.ceil(total)

    context = {
        "program": program,
        "corporation": program.corporation.corporation,
        "form": form,
        "data": data,
        "value": value,
        "typeids": typeids,
        "total": total,
        "program_location": program_location,
    }

    return render(request, "buybacks/program_calculate.html", context)


@login_required
@permission_required("buybacks.basic_access")
def program(request, program_pk):
    program = Program.objects.filter(pk=program_pk).first()

    if program is None:
        return redirect("buybacks:index")

    context = {
        "program": program,
        "items": ProgramItem.objects.filter(program=program),
        "locations": ProgramLocation.objects.filter(program=program),
        "corporation": program.corporation.corporation,
    }

    return render(request, "buybacks/program.html", context)


@login_required
@permission_required("buybacks.manage_programs")
def program_remove(request, program_pk):
    Program.objects.filter(pk=program_pk).delete()

    return redirect("buybacks:index")


@login_required
@permission_required("buybacks.manage_programs")
def program_remove_item(request, program_pk, item_type_pk):
    ProgramItem.objects.filter(
        program=program_pk,
        item_type=item_type_pk,
    ).delete()

    return redirect("buybacks:program", program_pk=program_pk)


@login_required
@permission_required("buybacks.manage_programs")
def program_remove_location(request, program_pk, office_pk):
    ProgramLocation.objects.filter(
        program=program_pk,
        office=office_pk,
    ).delete()

    return redirect("buybacks:program", program_pk=program_pk)


@login_required
@permission_required("buybacks.manage_programs")
def program_add_item(request, program_pk):
    program = Program.objects.filter(pk=program_pk).first()

    if program is None:
        return redirect("buybacks:index")

    if request.method != "POST":
        form = ProgramItemForm()
    else:
        form = ProgramItemForm(
            request.POST,
            value=int(request.POST["item_type"]),
        )

        if form.is_valid():
            item_type = form.cleaned_data["item_type"]
            brokerage = form.cleaned_data["brokerage"]
            use_refined_value = form.cleaned_data["use_refined_value"]

            try:
                _, created = ProgramItem.objects.update_or_create(
                    item_type=item_type,
                    program=program,
                    defaults={
                        "brokerage": brokerage,
                        "use_refined_value": use_refined_value,
                    },
                )

                if created:
                    messages_plus.success(
                        request,
                        format_html(
                            "Added <strong>{}</strong> to <strong>{}</strong>",
                            item_type,
                            program.name,
                        ),
                    )

                return redirect("buybacks:program", program_pk=program.id)

            except Exception:
                messages_plus.error(
                    request,
                    "Failed to add item to buyback program",
                )

    context = {
        "program": program,
        "corporation": program.corporation.corporation,
        "form": form,
    }

    return render(request, "buybacks/program_add_item.html", context)


@login_required
@permission_required("buybacks.manage_programs")
def program_add_location(request, program_pk):
    program = Program.objects.filter(pk=program_pk).first()

    if program is None:
        return redirect("buybacks:index")

    if request.method != "POST":
        form = ProgramLocationForm(program=program)
    else:
        form = ProgramLocationForm(request.POST, program=program)

        if form.is_valid():
            office = form.cleaned_data["office"]

            try:
                _, created = ProgramLocation.objects.update_or_create(
                    office=office, program=program
                )

                if created:
                    messages_plus.success(
                        request,
                        format_html(
                            "Added <strong>{}</strong> to <strong>{}</strong>",
                            office,
                            program.name,
                        ),
                    )

                return redirect("buybacks:program", program_pk=program.id)

            except Exception:
                messages_plus.error(
                    request,
                    "Failed to add location to buyback program",
                )

    context = {
        "program": program,
        "corporation": program.corporation.corporation,
        "form": form,
    }

    return render(request, "buybacks/program_add_location.html", context)


@login_required
@token_required(
    scopes=[
        "publicData",
    ]
)
@permission_required("buybacks.manage_programs")
def program_add(request, token):
    request.session[ADD_PROGRAM_TOKEN_TAG] = token.pk
    return redirect("buybacks:program_add_2")


@login_required
@permission_required("buybacks.manage_programs")
def program_add_2(request):
    if ADD_PROGRAM_TOKEN_TAG not in request.session:
        raise RuntimeError("Missing token in session")
    else:
        token = Token.objects.get(pk=request.session[ADD_PROGRAM_TOKEN_TAG])

    success = True
    token_char = EveCharacter.objects.get(character_id=token.character_id)

    try:
        corporation = Corporation.objects.get(corporation=token_char.corporation)
    except (Corporation.DoesNotExist, EveCorporationInfo.DoesNotExist):
        messages_plus.error(
            request,
            format_html(
                gettext_lazy(
                    "You need to setup your corp first before managing it's "
                    "buyback programs"
                )
            ),
        )
        success = False

    if success:
        if request.method != "POST":
            form = ProgramForm()
        else:
            form = ProgramForm(request.POST)

            if form.is_valid():
                name = form.cleaned_data["name"]

                try:
                    program = Program.objects.create(name=name, corporation=corporation)
                    messages_plus.success(
                        request,
                        format_html(
                            "Created buyback program <strong>{}</strong>",
                            program.name,
                        ),
                    )
                    return redirect("buybacks:program", program_pk=program.id)

                except Exception:
                    messages_plus.error(
                        request,
                        "Failed to create buyback program",
                    )

        context = {
            "corporation": corporation.corporation,
            "form": form,
            "to": reverse("buybacks:program_add_2"),
            "action": "Create",
        }

buybacks/templates/buybacks/index.html
{% extends 'buybacks/base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}
<div class="table-responsive">
    <table style="width: 100%; margin: auto;" class="table table-striped table-condensed">
        <thead>
            <tr>
                <th style="width: 45%;">{% trans "Buyback Program Name" %}</th>
                <th style="width: 20%;">{% trans "Corporation" %}</th>
                <th class="text-center" style="width: 35%;">{% trans "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for program in programs %}
            <tr>
                <td style="line-height: 35px;">{{ program.name }}</td>
                <td style="line-height: 35px;">{{ program.corporation.corporation }}</td>
                <td class="text-center">
                    <a class="btn btn-success btn-sm" href="{% url 'buybacks:program_calculate' program_pk=program.id %}">
                        Use
                    </a>
                    <a class="btn btn-primary btn-sm" href="{% url 'buybacks:program' program_pk=program.id %}">
                        View
                    </a>
                    {% if perms.buybacks.manage_programs %}
                    <a class="btn btn-info btn-sm" href="{% url 'buybacks:program_notifications' program_pk=program.id %}">
                        Notifications
                    </a>
                    <a class="btn btn-warning btn-sm" href="{% url 'buybacks:program_stats' program_pk=program.id %}">
                        Stats
                    </a>
                    <a class="btn btn-danger btn-sm" href="{% url 'buybacks:program_remove' program_pk=program.id %}">
                        Delete
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'buybacks:index' %}">{% trans "Buybacks" %}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% navactive request 'buybacks:my_notifications' %}">
                    <a href="{% url 'buybacks:my_notifications' %}">
                        My Notifications
                    </a>
                </li>
                <li class="{% navactive request 'buybacks:my_stats' %}">
                    <a href="{% url 'buybacks:my_stats' %}">
                        My Statistics
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if perms.buybacks.manage_programs %}
                    <a class="btn btn-default navbar-btn" href="{% url 'buybacks:program_add' %}">
                        Create Program
                    </a>
                {% endif %}
                {% if perms.buybacks.setup_retriever %}
                    <a class="btn btn-default navbar-btn" href="{% url 'buybacks:setup' %}">
                        Setup Corp
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

buybacks/templates/buybacks/notification_edit.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load number %}

{% block body %}
<form class="form" action="{% url 'buybacks:notification_edit' notification_pk=notification.id %}?mine={{ mine }}" method="POST">
  {% csrf_token %}
  {{ form|bootstrap }}

  <div style="text-align: center; margin-top: 20px;">
    <p class="text-muted">Total Contract Value: <span class="text-primary" id="total">{{ notification.total|format_number:0 }}</span> ISK</p>
  </div>

  <button type="submit" class="btn btn-primary">{% trans "Edit" %}</button>
</form>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/notifications.html
{% extends 'buybacks/base.html' %}
{% load i18n %}
{% load humanize %}
{% load dict %}
{% load number %}

{% block details %}
<div class="table-responsive">
    <table style="width: 100%; margin: auto;" class="table table-striped table-condensed">
        <thead>
            <tr>
                {% if not mine %}
                <th>{% trans "User" %}</th>
                {% endif %}
                <th>{% trans "Buyback Program" %}</th>
                <th>{% trans "Corporation" %}</th>
                <th>{% trans "Location" %}</th>
                {% if mine or perms.buybacks.manage_programs %}
                <th class="text-center">{% trans "Actions" %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for notification in bb_notifications %}
            <tr>
                {% if not mine %}
                <td style="line-height: 35px;">{{ notification.user.username }}</td>
                {% endif %}
                <td style="line-height: 35px;">{{ notification.program_location.program.name }}</td>
                <td style="line-height: 35px;">{{ notification.program_location.program.corporation }}</td>
                <td style="line-height: 35px;">{{ notification.program_location.office }}</td>
                {% if mine or perms.buybacks.manage_programs %}
                <td class="text-center">
                    <a class="btn btn-sm btn-warning" href="{% url 'buybacks:notification_edit' notification_pk=notification.id %}?mine={{ mine }}">
                        Edit
                    </a>
                    <a class="btn btn-sm btn-danger" href="{% url 'buybacks:notification_remove' notification_pk=notification.id %}?mine={{ mine }}">
                        Delete
                    </a>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td colspan="4" style="padding: 20px;">
                    <div class="table-responsive">
                        <table style="width: 60%; margin: auto;" class="table table-striped table-condensed">
                            <thead>
                                <tr>
                                    <th style="width: 75%">Item</th>
                                    <th style="width: 25%; text-align: center;">Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for id, quantity in notification.items|json|entries %}
                                <tr>
                                    <td>{{ items|lookup:id }}</td>
                                    <td style="text-align: right;">{{ quantity|format_number:0 }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <div style="text-align: center; margin-top: 20px;">
                            <p class="text-muted">Total Contract Value: <span class="text-primary" id="total">{{ notification.total|format_number:0 }}</span> ISK</p>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block body %}
<div class="pull-left">
  <h4>{{ program.name }} - Buyback Program</h4>
</div>

{% if perms.buybacks.manage_programs %}
<div class="pull-right">
  <a class="btn btn-sm btn-warning" href="{% url 'buybacks:program_edit' program_pk=program.id %}">
    Edit name
  </a>
  <a class="btn btn-sm btn-success" href="{% url 'buybacks:program_add_item' program_pk=program.id %}">
    Add item & price
  </a>
  <a class="btn btn-sm btn-success" href="{% url 'buybacks:program_add_location' program_pk=program.id %}">
    Add location
  </a>
</div>
{% endif %}

<div style="clear: both; padding-top: 20px; display: flex;" class="table-responsive">
  <table style="width: 60%;" class="table table-striped table-condensed">
      <thead>
          <tr>
              <th style="width: 60%;">{% trans "Item Type" %}</th>
              <th class="text-center" style="width: 10%;">{% trans "Brokerage" %}</th>
              <th class="text-center" style="width: 20%;">{% trans "Refined Value" %}</th>
              {% if perms.buybacks.manage_programs %}
              <th style="width: 10%;"></th>
              {% endif %}
          </tr>
      </thead>
      <tbody>
          {% for item in items %}
          <tr>
              <td>{{ item.item_type.name }}</td>
              <td class="text-center">{{ item.brokerage }}%</td>
              <td class="text-center">{{ item.use_refined_value }}</td>
              {% if perms.buybacks.manage_programs %}
              <td class="text-center">
                <a href="{% url 'buybacks:program_remove_item' program_pk=program.id item_type_pk=item.item_type.id %}">delete</a>
              </td>
              {% endif %}
          </tr>
          {% endfor %}
      </tbody>
  </table>

  <table style="width: 35%; margin-left: 20px;" class="table table-striped table-condensed">
    <thead>
        <tr>
            <th style="width: 90%;">{% trans "Location" %}</th>
            {% if perms.buybacks.manage_programs %}
            <th style="width: 10%;"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for location in locations %}
        <tr>
            <td>{{ location.office.location.name }}</td>
            {% if perms.buybacks.manage_programs %}
            <td>
              <a href="{% url 'buybacks:program_remove_location' program_pk=program.id office_pk=location.office.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program_add_item.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<form class="form" action="{% url 'buybacks:program_add_item' program_pk=program.id %}" method="POST">
  {% csrf_token %}
  {{ form|bootstrap }}
  <button type="submit" class="btn btn-primary">Add item</button>
</form>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybacks/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybacks/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program_calculate.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}
{% load dict %}
{% load number %}

{% block body %}
<h4>{{ program.name }} - Buyback Program</h4>

{% if value|not_empty %}
<div class="table-responsive" style="margin: 20px 0;">
    <p class="text-muted">Based on the contents you have given us, we have calculated them to be of the following value.</p>
    <p class="text-warning">Please click the <strong>Notify</strong> button to let us know you will be sending the contract.</p>

    <table id="value" style="width: 60%; margin: 20px auto;" class="table table-striped table-condensed">
        <thead>
            <tr>
                <th style="width: 55%">Item</th>
                <th style="width: 15%; text-align: center;">Quantity</th>
                <th style="width: 30%; text-align: center;">Value</th>
            </tr>
        </thead>
        <tbody>
            {% for item in value %}
            <tr>
                <td data-type-id="{{ typeids|lookup:item }}">{{ item }}</td>
                <td style="text-align: right;">{{ data|lookup:item|format_number:0 }}</td>
                <td style="text-align: right;">{{ value|lookup:item|format_number:2 }} ISK</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div style="text-align: center;">
        <p class="text-muted">Total Contract Value: <span class="text-primary" id="total">{{ total|format_number:0 }}</span> ISK</p>
        <button id="notify" data-program-location="{{ program_location.id }}" data-url="{% url 'buybacks:program_notify' program_pk=program.id %}" class="btn btn-warning btn-sm">Notify</button>
    </div>
</div>
{% endif %}

<form class="form" action="{% url 'buybacks:program_calculate' program_pk=program.id %}" method="POST">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit" class="btn btn-primary">Calculate</button>
  </form>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybacks/js/notify.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}